services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - "443:443"
    volumes:
      - /home/aletheios/data/wordpress:/var/www/html
    networks:
      - inception_net
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:443/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    volumes:
      - /home/aletheios/data/wordpress:/var/www/html
    networks:
      - inception_net
    healthcheck:
      test: ["CMD-SHELL", "pgrep php-fpm82 > /dev/null"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - /home/aletheios/data/mariadb:/var/lib/mysql
    networks:
      - inception_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "wp_user", "-p$(cat /run/secrets/db_password)"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    environment: 
      ADMINER_DEFAULT_SERVER: mariadb
      ADMINER_DESIGN: galkaev
    ports:
      - 8080:8080
    networks:
      - inception_net

  cv_server:
    build: ./requirements/bonus/cv_server
    container_name: cv_server
    ports:
      - 7777:7777
    networks:
      - inception_net

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt

networks:
  inception_net:
    driver: bridge
